[tool.poetry]
name = "pywebview-gui"
version = "0.1.0"
description = ""
authors = ["Sowul <bartosz.sowul@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pythonnet = "^3.0.3"
cefpython3 = "^66.1"
pywebview = "^5.1"
schedule = "^1.2.2"
python-fasthtml = "^0.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
